- name: Install docker-py
  tags: [proxy]
  pip:
    name: docker
    executable: pip

- name: Create the traefik container
  tags: [proxy]
  docker_container:
    name: traefik
    image: traefik:2.8
    restart_policy: unless-stopped
    recreate: true
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock