version: '3'
services:
  srv1:
    image: explabs/platform-example-service
    hostname: srv2
    ports:
      - "192.168.56.11:2022:22"
    runtime: sysbox-runc
  srv2:
    image: explabs/platform-example-service
    hostname: srv2
    ports:
      - "192.168.56.12:2022:22"
    runtime: sysbox-runc
