---

- name: restart docker
  tags: [deploy_tasks]
  service:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: restarted

- name: restart sshd
  tags: [deploy_tasks]
  systemd:
    name: sshd
    state: restarted